### PR TITLE
Complied as best as I could with 2015-04-13 instructions. Surprisingly tricky. :)

### PR DESCRIPTION
**Pull request by jbrains**
Read the README.md for details.

### CODE REVIEW

**Comment by patmaddox** [comment]
totally cool :)  you got it right. I'll have to review the instructions I sent out... because I sent them at 1:30 in the morning after a ridiculously long, stressful day, and I know they pretty much suck.

this is the beauty of this process to me though, already revealing itself. we have so many examples to follow!

**Comment by jbrains** [comment]
You da man. This is why we pair, even asynchronously.

**Comment by patmaddox** [comment]
a bit of info that's in my head, that didn't make it to the instructions, is that it's the folder prefix that matters... not the full name.

you can see some of the warmups that people did, and how there's variation in the names. `01` works, `01_day1` works, `01_so_excited_for_the_challenge` works...

of course we'll have more examples after today, too!

**Comment by jbrains** [comment]
:smile_cat:

**Pull request merged**
