### PR TITLE
The ant can walk forever, but can't tell black from white

### PR DESCRIPTION
**Pull request by jbrains**
I suppose it's a British ant, because it only ever turns left.

### CODE REVIEW

**Comment by jbrains** [comment]
Sorry that this is early for Day 7. I can't help the time zone I'm in. :)

**Comment by jbrains** [comment]
Somehow this got orphaned. I assume it was because I submitted it too early. Bump.

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
what do you mean "orphaned" ?

**Comment by jbrains** [comment]
Nevermind. Problem solved.

**Pull request merged**
