### PR TITLE
my warm-up README

### PR DESCRIPTION
**Pull request by wesr7**

### CODE REVIEW

**Comment by patmaddox** [comment]
@wesr7 get those warmup directories correctly named (with 01_ and 02_ prefixes) and I'll merge!

**Comment by wesr7** [comment]
i changed the the directory names

**Comment by patmaddox** [comment]
This pull request appears modify only your own files - nice work! Now it just needs final review from a human... (this comment was auto-generated :)

**Comment by patmaddox** [comment]
all good!

**Pull request merged**
