### PR TITLE
Added Day 5

### PR DESCRIPTION
**Pull request by skahlert**
Bugfix for previous day

### CODE REVIEW

**Comment by kotp** [comment]
There you are.  Did you investigate using UTC, as a fixed time zone should work.  The only thing that changes is the start date.  I think that is the only real moving part.

Are you considering creating a gem for this?

**Comment by skahlert** [comment]
Oh, haven't noticed the comment.
Yeah, I was thinking too much from the "Rails"-perspective, where I usually set up the project to use the local timezone. Working in UTC makes things easier, but you cannot automatically assume everyone has the same setup.

As for the gem: Not sure ... the utility value seems a bit low, don't you think?

**Comment by kotp** [comment]
You aren't assuming anyone has the same setup, you set it to UTC, the difference from current UTC to current MST or MDT is going to be universally the same.  No reliance on their local time zone, which is the point.

And definitely not too little utility value.  You should see how many gems are extremely small and focused.  If you don't want to push it to a gemserver, simply don't.  Anyone that pulls the RubySteps repository could go to your project folder and install it from the file system.

**Comment by patmaddox** [comment]
Go you!

**Comment by skahlert** [comment]
@kotp You're absolutely right! Of course the remaining time to the deadline is the same, no matter where you are :laughing: 
And why not... I'll make a gem. Haven't done anything with command-line scripts yet either, so it might be a good challenge for today. Thanks for the tip.

**Pull request merged**
