### PR TITLE
Day 5 challenge complete!

### PR DESCRIPTION
**Pull request by tommycarney**

### CODE REVIEW

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
awesome :) fyi in Ruby we typically indent with two spaces rather than tabs. don't let that stop you from coding though.. it's more important that you write code than worry about formatting (for now :)

**Comment by tommycarney** [comment]
Thanks for the heads up regarding the spaces vs tabs!

**Comment by kotp** [comment]
I thought to mention it quite a few times, and each time thought not to.  But if you have editor questions on how to do this, feel free to ask.  I am sure there is someone here that can help with that.  For my vim settings, I have a ftfplugin folder set up for Ruby that dictates that all tabs are expanded and are composed of 2 spaces.  (I use vim).  SublimeText is common and has similar settings.

**Comment by patmaddox** [comment]
@kotp considering the nits you do choose to pick I'm surprised that you bit your tongue on the spacing! it's a pretty fundamental / standardized thing in Ruby-land imo

**Comment by kotp** [comment]
I guess I should expand on the WHY I chose not to.  You see, I like the fact that tabs allow the viewer to decide to to view those tabs.  If I like having 8 'em' spacing for a tab, then I should be able to have that.  The author only cares that I get one tab, I care how that tab is presented to me as the the viewer/reader.

So I have a very mixed feeling about telling people to use two spaces rather than tabs.  Though for my code you will note that I very much as the author want you to get two spaces when viewing.  Call me a control freak... whatever.  But if you give me a tab, I will choose to view that tab as I wish, and I expect if I give you a tab, you will have an opinion on that as well.  (I also like to think that my whitespace at the end of lines is few and far between, as that shows a level of carelessness.)

Also, not knowing what editor they are using, opens up an area of discussion I wasn't quite ready for... so though the bloody tongue and the progression to my cheek for biting, I still held off until today.  But now that you brought it up, and they responded, then I know that they are at least interested in the potential arguments.

**Pull request merged**
