### PR TITLE
adds 02 dir and readme

### PR DESCRIPTION
**Pull request by 7sun**

### CODE REVIEW

**Comment by kotp** [comment]
:+1:

**Comment by patmaddox** [comment]
Your pull request contains changes to files outside of the challenge and warmup directories. Please fix it!

2_adventures/7sun/02/readme.md

**Comment by patmaddox** [comment]
@7sun the group challenge directory is `2_adventures/001` - meaning, adventure 001, for April. You need to place your personal sub-directory inside of it. Please see [the existing work](https://github.com/RubySteps/21-day-challenge/tree/master/2_adventures/001) - including [your own!](https://github.com/RubySteps/21-day-challenge/tree/master/2_adventures/001/7sun) ;)

**Comment by patmaddox** [comment]
looks like you have a completed day 02 so this is not necessary anymore. closing...

**Pull request closed without merging**
