### PR TITLE
Add README and begin testing code

### PR DESCRIPTION
**Pull request by liamseanbrady**
Cutting it close today!

Time is short at the moment, so I decided my project for the next couple of days will be to add some tests to @r11runner 's code from Day 1. I really liked it when I first saw it and thought it would be fun to play around with.

### CODE REVIEW

**Comment by patmaddox** [comment]
This pull request appears modify only your own files - nice work! Now it just needs final review from a human... (this comment was auto-generated :)

**Comment by ghost** [comment]
Thanks a lot :-)
It's good to see an improved version of my code. :)

**Comment by patmaddox** [comment]
awesome!!! Impromptu collaboration, adding tests to code... love it!

**Comment by kotp** [comment]
@r11runner I wonder if you could provide instructions on how to "merge" your code with the original code.  Would you use (can you use) git to do this?  Would you use `patch` to do this?  How to get changes in from other folders in a project to finally become one?

**Comment by ghost** [comment]
@kotp Sorry, I'm not sure I understand the question correctly. Do you mean how to merge the improvements from liamseanbrady with my original code?

**Comment by kotp** [comment]
Yeah, I think so, not knowing where the original files are... but yes, so that the original author can merge your commits to their solution.  So potentiall the other way around as well.

**Comment by kotp** [comment]
@liamseanbrady is the contributor, I see that you are the original author. :)

**Comment by kotp** [comment]
So the question really is to @r11runner  as well as to you.

**Comment by patmaddox** [comment]
In a "normal" project you would be working on the same file, and so there would be a clean commit history. Here, where copying files is pretty common, we don't have that.

In situations like this, I would advise giving credit to the original author via README and/or comments - and @liamseanbrady you did exactly that! So I think it's cool.

Now though, @liamseanbrady and @r11runner have an opportunity to take the collaboration a bit further... and perhaps start working on the same files.

In any case, I am _totally cool_ with how this played out. It's not important from a git perspective to see who wrote the original code... and @liamseanbrady assigned credit to @r11runner along with a link to the original file, via the README.

This will happen a lot - copying your own file from one day to the next, or even someone else's file as in this case. That's not something that would typically happen in a git workflow, but you can think of your daily exercise as being a journal entry... and if you copy someone else's entry in to yours before making changes - cool! :)

---

A related example that does happen in "real" projects from time to time: you copy a snippet of code you found on a blog somewhere. There's no merging to do, no git attribution, but you give credit via a comment.

**Comment by kotp** [comment]
I was more interested in 'clean' merges, and I would use `patch` to do so, It is fairly trival to use diff to generate the patch required and then apply and commit it.

It was a technical question, strictly.

I was considering using a `ln old_files new_files` to get day 4 things into day 5 area.  For me it is simpler as I control the flow.  For this situation a little bit more complex IF they want to coordinate.

**Comment by ghost** [comment]
@liamseanbrady
You changed

```
Dir.mkdir(path)
```

to

```
IO.popen("mkdir #{path}")
```

I've never used the IO.popen method, so it would be great, if you could explain to me why you prefer it in this case :-)

**Pull request merged**
