### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by ljnissen**

### CODE REVIEW

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
Can you share the story of your GitHub contributions getting noticed? :)

**Comment by ljnissen** [comment]
Sure, there was a recruiter who contacted me yesterday and he wants me to work for a Danish company with the ruby backend. He had seen what I have done here so definitely it's getting noticed!

**Comment by patmaddox** [comment]
awesome! let us know how it pans out :)

**Comment by ljnissen** [comment]
Sure, I will.

**Pull request merged**
