### PR TITLE
Create readme for first challenge

### PR DESCRIPTION
**Pull request by awochna**

### CODE REVIEW

**Comment by patmaddox** [comment]
@awochna please see the [README and examples from other users](https://github.com/RubySteps/21-day-challenge/tree/master/2_adventures/001) about how to structure the challenge files. You can absolutely have a top-level README of your own, but to meet the challenge criteria you need a directory for each day of the challenge.

Fix that up, and I'll merge this :)

**Comment by awochna** [comment]
Sorry about that @patmaddox. This latest commit should fix that up, for realzies.

**Comment by patmaddox** [comment]
This pull request appears modify only your own files - nice work! Now it just needs final review from a human... (this comment was auto-generated :)

**Comment by patmaddox** [comment]
lookin good, for realzies!

**Pull request merged**
