### PR TITLE
Day 17 challenge

### PR DESCRIPTION
**Pull request by aniruddhabarapatre**
Initial README commit

### CODE REVIEW

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
@aniruddhabarapatre this is the sort of pull request I'm trying to avoid when I say [pull requests should not end in a merge](https://github.com/RubySteps/21-day-challenge/wiki/Well-Formed-Pull-Requests).

See how there's 9 commits for only one file change? Not very clean...

Here's my suggestion to you to make it a nice, clean pull request:
1. Create a new branch by following the [suggested git workflow](https://github.com/RubySteps/21-day-challenge/wiki/Suggested-Git-Workflow)
2. Cherry-pick the day 17 commit with `git cherry-pick b63bb1a`

That should be it! Now your pull request will show only the one unique commit...

You can `git push -f` to this branch to blow away the extra commits... or you can close this pull request and open a new one.

Of course, if I've misunderstood the intent behind your pull request, please let me know!

**Comment by aniruddhabarapatre** [comment]
Don't know what's going on with this for last 3-4 days.
The workflow I follow is the one that's mentioned in wiki.

```
git branch // To check if I am on master
git pull upstream master // To get all the changes
git checkout -b newBranch
create and commit README
git push -u origin newBranch
```

Anything you think I am missing. I am supposed to do `git push -f` instead of `git push -u`?

**Comment by kotp** [comment]
This is the workflow that I have...

Taken from my command line history... I am sitting in my folder.  (Note that I have an alias for checkout called 'co')

```
git co master
git co -b 18_last_stretch
mkdir 18_another_day_another
cd 18_another_day_another
git status
touch README.md
echo "# Day 18\n" >> README.md
cat README.md
git add README.md
git commit -v
git push origin 18_last_stretch
git co master
cd ..
ls # making sure I am under my day 18 folder, otherwise I will be "in" a folder that doesn't exist.
git pull upstream master
git push origin master
```

This means that I don't take on the master branch from upstream until after I make my branch from the bit more stale master branch.

But I do take the project master and push it to my project after I create the work for today.

The sequence of events are repeated the next day.  This avoids having the commits that may or may not yet have been synchronized.  No rebase needed, just very careful what my branch is based on, and that it is not working pending a merge on the upstream repository.  If it is based on pending merges, then this means that @patmaddox or someone that has write access needs to do these things in a specific order.  I can't control the order, so I control what gets introduced in my new branch.

The main difference here is that you take on upstream before you do your new branch.  I wait to do so, after I create my new days work.  I have nothing that is required from upstream due to this, and am introducing nothing that upstream may not yet have, aside from the totally fresh work in my branch.

**Comment by aniruddhabarapatre** [comment]
@kotp Why did you do `git co master` after creating branch? Wouldn't all the code that's created be on master then?

**Comment by kotp** [comment]
Sorry, yeah, that got swapped around for some reason.  Fixed the order now.

**Comment by patmaddox** [comment]
@aniruddhabarapatre do you use the `--ff-only` option to ensure that the new stuff you pull is fast-forward only? because if not, it seems likely that it will create merge commits. that's why I suggest `ff-only`, so you can get immediate feedback if something is not right.

as for fixing this PR, I suggest creating a new branch directly off of upstream/master and cherry-pick your new commit...

**Comment by patmaddox** [comment]
closing because old

**Pull request closed without merging**
