### PR TITLE
Jk day 15

### PR DESCRIPTION
**Pull request by JonKernPA**
move and turn, baby

### CODE REVIEW

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
I don't understand what's going on with your pull requests... do you?

**Comment by JonKernPA** [comment]
no, i do not… 
the only different thing I did this time was:
- Added the code coverage results because I thought they might be cool for folks to see — but yes, not code-related, so I guess a violation of the rules
- I commented out the 14-day cucumber step refs so they wouldn’t show up in my RubyMine as I was working on 15-day code

Hmmmmm. 

_OH!!!_
I think because my day 13 and 14 were somehow missing when i did a `git pull upstream master`, I merged the local branches into my new work (e.g., 14_day --> 15_day) so I would have my code to start with again. I bet that messed things up!

**Comment by JonKernPA** [comment]
I want to abandon this pull request.

**Comment by patmaddox** [comment]
okay :)

**Pull request closed without merging**
