### PR TITLE
Day 16: GTK is slow.

### PR DESCRIPTION
**Pull request by jbrains**
I wish I'd known this at the start. I have no idea what to do about. Maybe tomorrow I'll research it. Exponential curves kill.

### CODE REVIEW

**Comment by patmaddox** [comment]
Your pull request contains changes to files outside of the challenge and warmup directories. Please fix it!

1_warmup/Dino-Herbert/01_warmup/Readme.md
1_warmup/Dino-Herbert/02_warmup/Readme.md
1_warmup/airportyh/01/README.md
1_warmup/airportyh/02/README.md
1_warmup/alexsimmons1964/01/README.md
1_warmup/alexsimmons1964/02/README.md
1_warmup/avalade/01_first_warmup/README.md
1_warmup/avalade/02/README.md
1_warmup/domhede/01_warmer/README.md
1_warmup/domhede/02_warmer_still/README.md
1_warmup/gspederson/01/README.md
1_warmup/gspederson/02/README.md
1_warmup/kangkyu/01/README.md
1_warmup/kangkyu/02/README.md
1_warmup/ljnissen/01/README.md
1_warmup/ljnissen/02_LJ_loves_to_code/README.md
1_warmup/mtthwhggns/01/README.md
1_warmup/mtthwhggns/02/README.md
1_warmup/mtthwhggns/go.rb
1_warmup/ravi279/01-first-warmup/README.md
1_warmup/ravi279/02-second-warmup/README.md
1_warmup/ravi279/03-third-warmup/README.md
1_warmup/ravi279/04-fourth-warmup/README.md
1_warmup/ravi279/05-fifth-warmup/README.md
1_warmup/ravi279/06-sixth-warmup/README.md
1_warmup/ravi279/07-seventh-warmup/README.md
1_warmup/ravi279/08-eigth-warmup/README.md
1_warmup/ravi279/09-ninth-warmup/README.md
2_adventures/001/7sun/03/Readme.md
2_adventures/001/7sun/03/date-suffix/date-suffix.rb
2_adventures/001/7sun/04/Readme.md
2_adventures/001/Dino-Herbert/01/01_warmup/Readme.md
2_adventures/001/Dino-Herbert/01/02_warmup/Readme.md
2_adventures/001/Dino-Herbert/01/Readme.md
2_adventures/001/Dino-Herbert/02/Number_Hole_puzzle.rb
2_adventures/001/Dino-Herbert/02/Readme.md
2_adventures/001/Dino-Herbert/03/Readme.md
2_adventures/001/Dino-Herbert/03/testscrape.rb
2_adventures/001/Dino-Herbert/04_Day4/Readme.md
2_adventures/001/Dino-Herbert/04_Day4/reg_exp_test.rb
2_adventures/001/Dino-Herbert/04_Day4/test_html.html
2_adventures/001/Dino-Herbert/05_Apr18/Readme.md
2_adventures/001/Dino-Herbert/05_Apr18/reg_exp_test2.rb
2_adventures/001/Dino-Herbert/07_Apr19/MLBscores2015-04-19.txt
2_adventures/001/Dino-Herbert/07_Apr19/MLBscores2015-04-19new.txt
2_adventures/001/Dino-Herbert/07_Apr19/MLBscores2015-04-19old.txt
2_adventures/001/Dino-Herbert/07_Apr19/Readme.md
2_adventures/001/Dino-Herbert/07_Apr19/reg_exp_test3.rb
2_adventures/001/Dino-Herbert/07_Apr19/reg_exp_test4.rb
2_adventures/001/Dino-Herbert/09_Apr21/3_jars.rb
2_adventures/001/Dino-Herbert/09_Apr21/Readme.md
2_adventures/001/Dino-Herbert/10_Apr22/3_jars_v2.rb
2_adventures/001/Dino-Herbert/10_Apr22/3_jars_v3.rb
2_adventures/001/Dino-Herbert/10_Apr22/3_jars_v4.rb
2_adventures/001/Dino-Herbert/10_Apr22/Readme.md
2_adventures/001/Randhir123/02/README.md
2_adventures/001/Randhir123/02/variables.rb
2_adventures/001/Randhir123/03/README.md
2_adventures/001/Randhir123/03/files.rb
2_adventures/001/Randhir123/04/README.md
2_adventures/001/Randhir123/04/dict.rb
2_adventures/001/Randhir123/05/05.gemspec
2_adventures/001/Randhir123/05/README.md
2_adventures/001/Randhir123/05/Rakefile
2_adventures/001/Randhir123/05/bin/05
2_adventures/001/Randhir123/05/lib/05.rb
2_adventures/001/Randhir123/05/lib/05/fibonacci.rb
2_adventures/001/Randhir123/05/tests/test_05.rb
2_adventures/001/Randhir123/06/06.gemspec
2_adventures/001/Randhir123/06/README.md
2_adventures/001/Randhir123/06/Rakefile
2_adventures/001/Randhir123/06/bin/06
2_adventures/001/Randhir123/06/data/lexicon/direction.txt
2_adventures/001/Randhir123/06/data/lexicon/noun.txt
2_adventures/001/Randhir123/06/data/lexicon/stop.txt
2_adventures/001/Randhir123/06/data/lexicon/verb.txt
2_adventures/001/Randhir123/06/lib/06.rb
2_adventures/001/Randhir123/06/lib/06/lexicon.rb
2_adventures/001/Randhir123/06/lib/06/lexicon_type.rb
2_adventures/001/Randhir123/06/tests/test_06.rb
2_adventures/001/Randhir123/07/07.gemspec
2_adventures/001/Randhir123/07/README.md
2_adventures/001/Randhir123/07/Rakefile
2_adventures/001/Randhir123/07/bin/07
2_adventures/001/Randhir123/07/lib/07.rb
2_adventures/001/Randhir123/07/lib/07/funny.rb
2_adventures/001/Randhir123/07/tests/test_07.rb
2_adventures/001/Randhir123/08/README.md
2_adventures/001/Randhir123/08/images.rb
2_adventures/001/Randhir123/09/09.gemspec
2_adventures/001/Randhir123/09/README.md
2_adventures/001/Randhir123/09/Rakefile
2_adventures/001/Randhir123/09/bin/09
2_adventures/001/Randhir123/09/lib/09.rb
2_adventures/001/Randhir123/09/lib/09/storecredit.rb
2_adventures/001/Randhir123/09/lookup.rb
2_adventures/001/Randhir123/09/tests/test_09.rb
2_adventures/001/Randhir123/10/10.gemspec
2_adventures/001/Randhir123/10/README.md
2_adventures/001/Randhir123/10/Rakefile
2_adventures/001/Randhir123/10/bin/10
2_adventures/001/Randhir123/10/lib/10.rb
2_adventures/001/Randhir123/10/lib/10/spelling.rb
2_adventures/001/Randhir123/10/tests/test_10.rb
2_adventures/001/Randhir123/11/11.gemspec
2_adventures/001/Randhir123/11/11.rb
2_adventures/001/Randhir123/11/README.md
2_adventures/001/Randhir123/11/Rakefile
2_adventures/001/Randhir123/11/bin/11
2_adventures/001/Randhir123/11/lib/11.rb
2_adventures/001/Randhir123/11/lib/11/minimum_scalar_product.rb
2_adventures/001/Randhir123/11/tests/test_11.rb
2_adventures/001/Randhir123/12/12.rb
2_adventures/001/Randhir123/12/README.md
2_adventures/001/Randhir123/13/13.rb
2_adventures/001/Randhir123/13/README.md
2_adventures/001/afbroman/04/README.md
2_adventures/001/afbroman/04/react-rails-play/.gitignore
2_adventures/001/afbroman/04/react-rails-play/Gemfile
2_adventures/001/afbroman/04/react-rails-play/Gemfile.lock
2_adventures/001/afbroman/04/react-rails-play/README.md
2_adventures/001/afbroman/04/react-rails-play/Rakefile
2_adventures/001/afbroman/04/react-rails-play/app/assets/images/.keep
2_adventures/001/afbroman/04/react-rails-play/app/assets/javascripts/application.js.coffee
2_adventures/001/afbroman/04/react-rails-play/app/assets/javascripts/start.coffee
2_adventures/001/afbroman/04/react-rails-play/app/assets/stylesheets/application.css
2_adventures/001/afbroman/04/react-rails-play/app/assets/stylesheets/start.scss
2_adventures/001/afbroman/04/react-rails-play/app/controllers/application_controller.rb
2_adventures/001/afbroman/04/react-rails-play/app/controllers/concerns/.keep
2_adventures/001/afbroman/04/react-rails-play/app/controllers/start_controller.rb
2_adventures/001/afbroman/04/react-rails-play/app/helpers/application_helper.rb
2_adventures/001/afbroman/04/react-rails-play/app/helpers/start_helper.rb
2_adventures/001/afbroman/04/react-rails-play/app/mailers/.keep
2_adventures/001/afbroman/04/react-rails-play/app/models/.keep
2_adventures/001/afbroman/04/react-rails-play/app/models/concerns/.keep
2_adventures/001/afbroman/04/react-rails-play/app/views/layouts/application.html.erb
2_adventures/001/afbroman/04/react-rails-play/app/views/start/index.html.erb
2_adventures/001/afbroman/04/react-rails-play/bin/bundle
2_adventures/001/afbroman/04/react-rails-play/bin/rails
2_adventures/001/afbroman/04/react-rails-play/bin/rake
2_adventures/001/afbroman/04/react-rails-play/bin/setup
2_adventures/001/afbroman/04/react-rails-play/bin/spring
2_adventures/001/afbroman/04/react-rails-play/config.ru
2_adventures/001/afbroman/04/react-rails-play/config/application.rb
2_adventures/001/afbroman/04/react-rails-play/config/boot.rb
2_adventures/001/afbroman/04/react-rails-play/config/database.yml
2_adventures/001/afbroman/04/react-rails-play/config/environment.rb
2_adventures/001/afbroman/04/react-rails-play/config/environments/development.rb
2_adventures/001/afbroman/04/react-rails-play/config/environments/production.rb
2_adventures/001/afbroman/04/react-rails-play/config/environments/test.rb
2_adventures/001/afbroman/04/react-rails-play/config/initializers/assets.rb
2_adventures/001/afbroman/04/react-rails-play/config/initializers/backtrace_silencers.rb
2_adventures/001/afbroman/04/react-rails-play/config/initializers/cookies_serializer.rb
2_adventures/001/afbroman/04/react-rails-play/config/initializers/filter_parameter_logging.rb
2_adventures/001/afbroman/04/react-rails-play/config/initializers/inflections.rb
2_adventures/001/afbroman/04/react-rails-play/config/initializers/mime_types.rb
2_adventures/001/afbroman/04/react-rails-play/config/initializers/session_store.rb
2_adventures/001/afbroman/04/react-rails-play/config/initializers/wrap_parameters.rb
2_adventures/001/afbroman/04/react-rails-play/config/locales/en.yml
2_adventures/001/afbroman/04/react-rails-play/config/routes.rb
2_adventures/001/afbroman/04/react-rails-play/config/secrets.yml
2_adventures/001/afbroman/04/react-rails-play/db/seeds.rb
2_adventures/001/afbroman/04/react-rails-play/lib/assets/.keep
2_adventures/001/afbroman/04/react-rails-play/lib/tasks/.keep
2_adventures/001/afbroman/04/react-rails-play/log/.keep
2_adventures/001/afbroman/04/react-rails-play/public/404.html
2_adventures/001/afbroman/04/react-rails-play/public/422.html
2_adventures/001/afbroman/04/react-rails-play/public/500.html
2_adventures/001/afbroman/04/react-rails-play/public/favicon.ico
2_adventures/001/afbroman/04/react-rails-play/public/robots.txt
2_adventures/001/afbroman/04/react-rails-play/test/controllers/.keep
2_adventures/001/afbroman/04/react-rails-play/test/controllers/start_controller_test.rb
2_adventures/001/afbroman/04/react-rails-play/test/fixtures/.keep
2_adventures/001/afbroman/04/react-rails-play/test/helpers/.keep
2_adventures/001/afbroman/04/react-rails-play/test/integration/.keep
2_adventures/001/afbroman/04/react-rails-play/test/mailers/.keep
2_adventures/001/afbroman/04/react-rails-play/test/models/.keep
2_adventures/001/afbroman/04/react-rails-play/test/test_helper.rb
2_adventures/001/afbroman/04/react-rails-play/vendor/assets/javascripts/.keep
2_adventures/001/afbroman/04/react-rails-play/vendor/assets/stylesheets/.keep
2_adventures/001/afbroman/05/README.md
2_adventures/001/afbroman/06/README.md
2_adventures/001/afbroman/06/functional.js
2_adventures/001/afbroman/07/README.md
2_adventures/001/afbroman/07/index.html
2_adventures/001/afbroman/07/script.js
2_adventures/001/afbroman/08/README.md
2_adventures/001/afbroman/08/database_info.rb
2_adventures/001/afbroman/09/README.md
2_adventures/001/afbroman/10/Gemfile
2_adventures/001/afbroman/10/Gemfile.lock
2_adventures/001/afbroman/10/README.md
2_adventures/001/afbroman/10/database_connect.rb
2_adventures/001/afbroman/11/README.md
2_adventures/001/afbroman/11/binary_tree.rb
2_adventures/001/afbroman/11/binary_tree_demo.rb
2_adventures/001/afbroman/11/binary_tree_maze.png
2_adventures/001/afbroman/11/cell.rb
2_adventures/001/afbroman/11/grid.rb
2_adventures/001/afbroman/11/sidewinder.rb
2_adventures/001/afbroman/11/sidewinder_demo.rb
2_adventures/001/afbroman/11/sidewinder_maze.png
2_adventures/001/afbroman/12/README.md
2_adventures/001/afbroman/13/README.md
2_adventures/001/afbroman/13/opioid_data.rb
2_adventures/001/afbroman/13/opioids.csv
2_adventures/001/afbroman/13/who_populations.csv
2_adventures/001/afbroman/14/README.md
2_adventures/001/afbroman/14/index.html
2_adventures/001/afbroman/14/opioid_data.rb
2_adventures/001/afbroman/14/opioids.csv
2_adventures/001/afbroman/14/style.css
2_adventures/001/afbroman/15/README.md
2_adventures/001/afbroman/15/index.html
2_adventures/001/afbroman/15/opioids.csv
2_adventures/001/afbroman/15/style.css
2_adventures/001/ahmednadar/01_day1/README.md
2_adventures/001/ahmednadar/02_introduction/README.md
2_adventures/001/ahmednadar/03_seeding/README.md
2_adventures/001/ahmednadar/04_speed_with_emmet/README.md
2_adventures/001/ahmednadar/05_select_ruby/README.md
2_adventures/001/ahmednadar/06_all_method/README.md
2_adventures/001/ahmednadar/06_all_method/lib/all_method.rb
2_adventures/001/ahmednadar/06_all_method/test/all_method_test.rb
2_adventures/001/ahmednadar/07_binary_calculator/README.md
2_adventures/001/ahmednadar/07_binary_calculator/lib/binary_calculator.rb
2_adventures/001/ahmednadar/07_binary_calculator/test/binary_calculator_test.rb
2_adventures/001/alexander-ruehle/03_code_kata_karate_chop/README.md
2_adventures/001/alexander-ruehle/03_code_kata_karate_chop/chop.rb
2_adventures/001/alexander-ruehle/03_code_kata_karate_chop/chop_test.rb
2_adventures/001/alexsimmons1964/01/README.md
2_adventures/001/alexsimmons1964/02/README.md
2_adventures/001/alexsimmons1964/03/.gitkeep
2_adventures/001/alexsimmons1964/04/README.md
2_adventures/001/alexsimmons1964/05/README.md
2_adventures/001/alexsimmons1964/05/terminal_commands.md
2_adventures/001/alexsimmons1964/06/README.md
2_adventures/001/alexsimmons1964/07/README.md
2_adventures/001/alexsimmons1964/08/README.md
2_adventures/001/alexsimmons1964/09/README.md
2_adventures/001/alexsimmons1964/10/README.md
2_adventures/001/alexsimmons1964/11/README.md
2_adventures/001/alexsimmons1964/12/README.md
2_adventures/001/alexsimmons1964/13/README.md
2_adventures/001/alexsimmons1964/14/README.md
2_adventures/001/alexsimmons1964/15/README.md
2_adventures/001/amaliahern/03/README.md
2_adventures/001/amaliahern/04/README.md
2_adventures/001/amaliahern/04/fizz_buzz.rb
2_adventures/001/amaliahern/04/fizz_buzz_spec.rb
2_adventures/001/amaliahern/05/README.md
2_adventures/001/amaliahern/05/fizz_buzz.rb
2_adventures/001/amaliahern/05/fizz_buzz_spec.rb
2_adventures/001/amaliahern/06/README.md
2_adventures/001/amaliahern/06/fizz_buzz.rb
2_adventures/001/amaliahern/06/fizz_buzz_spec.rb
2_adventures/001/amaliahern/07/README.md
2_adventures/001/amaliahern/07/fizz_buzz.rb
2_adventures/001/amaliahern/07/fizz_buzz_rspec.rb
2_adventures/001/amaliahern/08/README.md
2_adventures/001/amaliahern/08/fizzbuzzdazzkezz.rb
2_adventures/001/amaliahern/09/README.md
2_adventures/001/amaliahern/09/roman_numerals.rb
2_adventures/001/amaliahern/09/roman_numerals_spec.rb
2_adventures/001/amaliahern/10/README.md
2_adventures/001/amaliahern/10/roman_numerals.rb
2_adventures/001/amaliahern/10/roman_numerals_spec.rb
2_adventures/001/amaliahern/11/README.md
2_adventures/001/amaliahern/11/roman_numerals.rb
2_adventures/001/amaliahern/11/roman_numerals_spec.rb
2_adventures/001/amaliahern/12/README.md
2_adventures/001/amaliahern/13/README.md
2_adventures/001/amaliahern/14/.kata_chop.rb.swp
2_adventures/001/amaliahern/14/README.md
2_adventures/001/amaliahern/14/kata_chop.rb
2_adventures/001/amaliahern/14/kata_chop_spec.rb
2_adventures/001/amaliahern/15/README.md
2_adventures/001/amaliahern/15/kata_chop.rb
2_adventures/001/amaliahern/15/kata_chop_spec.rb
2_adventures/001/avalade/01/Gemfile
2_adventures/001/avalade/01/Gemfile.lock
2_adventures/001/avalade/01/README.md
2_adventures/001/avalade/01/lib/hulk.rb
2_adventures/001/avalade/01/test/hulk/test_hulk.rb
2_adventures/001/awochna/.gitignore
2_adventures/001/awochna/03_post_a_tweet/Gemfile
2_adventures/001/awochna/03_post_a_tweet/Gemfile.lock
2_adventures/001/awochna/03_post_a_tweet/access_tokens.yml
2_adventures/001/awochna/03_post_a_tweet/tw
2_adventures/001/awochna/04_retrieve_some_tweets/.gitignore
2_adventures/001/awochna/04_retrieve_some_tweets/Gemfile
2_adventures/001/awochna/04_retrieve_some_tweets/Gemfile.lock
2_adventures/001/awochna/04_retrieve_some_tweets/README.md
2_adventures/001/awochna/04_retrieve_some_tweets/access_tokens.yml.example
2_adventures/001/awochna/04_retrieve_some_tweets/tw
2_adventures/001/awochna/05_rake_twitter_information/.gitignore
2_adventures/001/awochna/05_rake_twitter_information/Gemfile
2_adventures/001/awochna/05_rake_twitter_information/Gemfile.lock
2_adventures/001/awochna/05_rake_twitter_information/README.md
2_adventures/001/awochna/05_rake_twitter_information/Rakefile
2_adventures/001/awochna/05_rake_twitter_information/access_tokens.yml.example

---

Where's the README? :(

**Comment by patmaddox** [comment]
yikes looks like a bad merge in here somewhere. I wonder what happened? I've seen @JonKernPA have a couple pull requests like this too... either of you have any idea what's going on?

**Comment by JonKernPA** [comment]
Just now, I did the following workflow — is it the “ff-only” option that screws it up?

ruby-2.2.1 ~/railsprojects/21-day-challenge/2_adventures/001/jonkernpa/16_day on [jk-day-16*]
$ gst
On branch jk-day-16
Your branch is up-to-date with 'origin/jk-day-16'.

ruby-2.2.1 ~/railsprojects/21-day-challenge/2_adventures/001/jonkernpa/16_day on [jk-day-16_]
$ gcom
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 1261 commits.
  (use "git push" to publish your local commits)
ruby-2.2.1 ~/railsprojects/21-day-challenge/2_adventures/001/jonkernpa/16_day on [master_]
$ git pull --ff-only upstream master
remote: Counting objects: 567, done.
remote: Compressing objects: 100% (167/167), done.
remote: Total 567 (delta 150), reused 58 (delta 58), pack-reused 341

And when I went to push in RubyMine, the dang thing showed way more than I can imagine:

jon

blog: http://technicaldebt.com
twitter: http://twitter.com/JonKernPA
github: https://github.com/JonKernPA

**Comment by patmaddox** [comment]
I don't think it's the `ff-only` that screws it up... it's just a flag that makes git reject a pull if it's not a fast-forward.

It looks to me like the problem happens before the pull... you run `gcom` and it reports `Your branch is ahead of 'origin/master' by 1261 commits`. Whatever happened, it looks like it was before the pull.

My best guess is that it's a rebase gone wrong somewhere... do you happen to know the commands you ran before the stuff you shared here?

Also I'm wondering if perhaps it's a RubyMine configuration that's throwing it off...

**Comment by jbrains** [comment]
I don't know what happened. I pull upstream/master into my master, then branch, then push the branch and create a pull request from it. I'll pay more attention on the next one.

**Comment by JonKernPA** [comment]
That’s what I do as well.

https://github.com/RubySteps/21-day-challenge/pull/773

jon

blog: http://technicaldebt.com
twitter: http://twitter.com/JonKernPA
github: https://github.com/JonKernPA

**Comment by patmaddox** [comment]
@JonKernPA @jbrains when you pull, do you use the `--ff-only` option as I recommend? **I highly suggest putting it in your .git/config** as documented in the [suggested git workflow](https://github.com/RubySteps/21-day-challenge/wiki/Suggested-Git-Workflow) so that you don't forget it...

If you forget to use `--ff-only` then git will do a merge, which looks to me like the most likely thing that would cause this sort of commit log.

**Comment by jbrains** [comment]
Will do.

**Comment by JonKernPA** [comment]
yes, i do use that —ff-only

the last couple/few days, i did not bother doing git pull —ff-only upstream master

jon

blog: http://technicaldebt.com
twitter: http://twitter.com/JonKernPA
github: https://github.com/JonKernPA

**Pull request merged**
