### PR TITLE
First warmup exercise.

### PR DESCRIPTION
**Pull request by aldraco**

### CODE REVIEW

**Comment by patmaddox** [comment]
getting closer... :)  remember, each stage of the warmup (and the challenge itself!) goes in its own dir. so while it's totally cool for you to have a README in your personal directory, you need a sub-directory & README for each stage.

so you'll want something in `1_warmup/aldraco/01/README.md` - make sense?

**Comment by aldraco** [comment]
ah yes, I see now.
I promise I can read. :)

I will amend and resubmit...

**Comment by patmaddox** [comment]
this is why we have the warmup! :)

**Comment by aldraco** [comment]
Yes, that makes complete sense - I thought my github skills were a bit better than they are, apparently!!

**Comment by patmaddox** [comment]
it looks like you have a typo (README.ms instead of .md) but it's good enough for me! feel free to change it if you want, but you don't need to :)

**Comment by patmaddox** [comment]
oh yeah... you're all warmed up now!

**Pull request merged**
