### PR TITLE
Day3

### PR DESCRIPTION
**Pull request by Dino-Herbert**
For review

### CODE REVIEW

**Comment by kotp** [comment]
The `3_heroes` folder should not be touched at all.

There should be 4 pull requests.  Two individual pull requests for the warmup exercises. and then one each for day 2 and day 3.

The folder that you will effect is the `2_adventures/001/Dino-Herbert` folder in every case.  With the proper subfolders.

For a decent example of this, check out [patmaddox](https://github.com/RubySteps/21-day-challenge/tree/master/2_adventures/001/patmaddox) folder.

**Comment by Dino-Herbert** [comment]
Hey kotp,

Thanks for the clarification!

**Comment by patmaddox** [comment]
Your pull request contains changes to files outside of the challenge and warmup directories. Please fix it!

3_heroes/dino-herbert/01/01_warmup/readme.md
3_heroes/dino-herbert/01/02_warmup/readme.md
3_heroes/dino-herbert/02/number_hole_puzzle.rb
3_heroes/dino-herbert/02/readme.md
3_heroes/dino-herbert/03/readme.md
3_heroes/dino-herbert/03/testscrape.rb

**Comment by patmaddox** [comment]
yep as @kotp mentioned, we're working only in the `2_adventures/001` folder... also please see the comment from #260 about your day 1 example. You'll get the hang of it quick!

**Pull request merged**
