### PR TITLE
Day 13... 1h20 late... :(

### PR DESCRIPTION
**Pull request by tooky**

### CODE REVIEW

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
my guess is anyone who sticks it out through all 21 days will get credit... this stuff is hard, it's the first time, and I don't exactly have very good tooling to help people figure out where they stand ;)  keep it up!

**Comment by tooky** [comment]
@patmaddox Thanks! I'd have kept going anyway :)

Weekdays and weekend-days are definitely a different kettle of fish for me. Weekends are much less structured, and I have to fit in around the family as I'm busy during the week. I don't have a solution, but I guess some leeway would help... maybe as you automate, the timing can be more relaxed over the weekend?

Thanks for the challenge though, I'm enjoying being involved.

**Comment by patmaddox** [comment]
@tooky the solution, for crazy days, is to touch a README, send your pull request, and call it a day :)  it takes 5 minutes max... and I'm not even going to pretend that 5 minutes is "totally doable" because I know some days it's not - I don't call it a challenge for nothing! ;)

**Comment by kotp** [comment]
I know three people at least are using the program that @skahlert made to help keep track of the time.  What my strategy has been is that one time per day, I try to get in the readme file and push it up.  Once pushed up, I go to the browser and hit that pull request.  If I can get to more for the challenge specifically, then I have at least done the readme and can push up another change.  This "locks me in" for that 24 hour period.  If I have more time, great.  If not, still great!.

**Pull request merged**
