### PR TITLE
Shamash's first warmup

### PR DESCRIPTION
**Pull request by Shamash2014**
Hi! 

My first warmup before 21 day challenge

### CODE REVIEW

**Comment by patmaddox** [comment]
Your pull request contains changes to files outside of the challenge and warmup directories. Please fix it!

1_warmup/shamash/01/README.md

**Comment by patmaddox** [comment]
@Shamash2014 hey looks like the problem here is that your folder name doesn't match your GitHub username. Please change the folder name and I'll be able to merge this!

**Comment by Shamash2014** [comment]
Fix it) And add second warmup) 
Thanks, @patmaddox

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
all good! see you in June :)

**Pull request merged**
