### PR TITLE
Day7 update

### PR DESCRIPTION
**Pull request by Dino-Herbert**

### CODE REVIEW

**Comment by kotp** [comment]
I notice that you have many branches that are very similar, as in Day7_*.  You can do updates on the same branch.  It will update your pull request.

**Comment by Dino-Herbert** [comment]
I have to admit I'm still unclear on how git responds to my changes.  So after I make a change locally, I should just push to the same branch name that I used the first time?  I created another branch (twice) because git told me that 'everything is up to date', even though I knew that it wasn't

**Comment by kotp** [comment]
If you are on day 7, for example, if you create a branch 07_some_information_you_would_like and do some work there, do a pull request, and realize there is more work to do on that branch, then your pushes to that same branch will simply update that pull request.

**Comment by kotp** [comment]
When it says you are up to date, do a `git push origin <branch_name>` anyway...  (Do a pull first and then a push... in case you are working with others).  Also, I am not sure (I haven't checked your repository to see) you may want to do upstream tracking as well.  You will then know when the pull request has made it to master.

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
@Dino-Herbert what command did you run when you got the "everything up to date" ? Was it the same "git push origin BRANCH_NAME" or just "git push" ?

It all depends on how your remotes are set up and how git is tracking branches... can be a bit complex to understand at first. If you have trouble I suggest creating an issue w/ the exact commands you run and output you get.

**Pull request merged**
