### PR TITLE
Day 06

### PR DESCRIPTION
**Pull request by askl56**
Back in black :)

### CODE REVIEW

**Comment by kotp** [comment]
@askl56  Should be in folder `2_adventures/001/<yourname>/06<_whatever_long_description_you_want>`

**Comment by kotp** [comment]
Now that the `.DS_Store` files are gone, you can add that to your global .gitignore and they won't be a problem any longer.

Here are some [sample gitignore files](github.com/github/gitignore).

**Comment by askl56** [comment]
Let me know if this is fixed

**Comment by kotp** [comment]
This PR doesnt' report that it is in the 001 folder.  Everything else looks good though, aside from that base folder being out of place.

**Comment by kotp** [comment]
`2_adventures/askl56/06_day6/tests.rb` for example... should be reporting as `2_adventures/001/askl56/06_day6/tests.rb` to reflect the very first 21 day adventure ever.

**Comment by askl56** [comment]
So I need a 01 folder?

**Comment by kotp** [comment]
001 folder.  You can see the pattern by viewing the source at [2_adventures](https://github.com/RubySteps/21-day-challenge/tree/master/2_adventures) and you will note that there is only that folder and a README.  Everything else goes under that 001 folder.

Click on Pat's folder and click on yours (in RubySteps repository (browse code) and you will see how they are the same in structure, then look at these folders for this PR and notice the difference.

The one pull request that was accepted looks like "/2_adventures/001/askl56/01_day1"

Your current files for this pull request look like this "/2_adventures/askl56/02_day2"

**Comment by askl56** [comment]
Let me know if that fixed it

**Comment by kotp** [comment]
Close... the 001 folder is after your name, rather than before it.  

In the parts of the name for the folders, you would have `RubySteps/2_adventures/001/askl56/07_folder_of_the_day`

**Comment by patmaddox** [comment]
Your pull request contains changes to files outside of the challenge and warmup directories. Please fix it!

.DS_Store
2_adventures/.DS_Store
2_adventures/README.md
2_adventures/askl56/.DS_Store
2_adventures/askl56/001/06_day6/readme.md
2_adventures/askl56/001/06_day6/tests.rb
2_adventures/askl56/01_day1/readme.md

---

Where's the README? :(

**Comment by patmaddox** [comment]
@askl56 this looks good to me (and don't worry about the checked-fail label, because the script is not smart enough to see that you deleted .DS_Store files...)

However, as you can see here "We can't automatically merge this pull request" so it looks like you'll need to do a bit of work to resolve the merge conflict... feel free to comment in here or on gitter if you need some help with it.

**Comment by patmaddox** [comment]
closing because old

**Pull request closed without merging**
