### PR TITLE
Feedback from PR: #283

### PR DESCRIPTION
**Pull request by kotp**
Dried the tests, just to make it simpler to make changes.

I want to add a message entry in the collection as well, to help
identify the edge cases, such as 0 which should show all replacements,
and the bases, such as 3 and 5, or -3 and -5.

re: #283

### CODE REVIEW

**Comment by kotp** [comment]
@lenn4rd  To continue from your feedback, and probably introduce more. :)

**Comment by patmaddox** [comment]
Where's the README? :(

**Comment by kotp** [comment]
The readme is not needed, as it is not a DAY push.

**Comment by patmaddox** [comment]
I saw and already merged

**Comment by lenn4rd** [comment]
I'll continue writing here, hope that's okay. Regarding the default rules for `initialize`: Providing default values for parameters is perfectly acceptably if you save yourself some code within the mode to sanity-check the params. Also it eases using this method in other parts of your program because you're able to call it without a parameter and you don't have to do something like `my_method(nil)`.

In this case the rule set is immutable which makes it a perfect candidate for a class constant. The top of `FizzBuzz` would look like this:

``` ruby
class FizzBuzz
  RULES = { 3 => 'Fizz', 5 => 'Buzz' }

  def initialize
    # no need to set @rules here, you can use RULES instead
  end

  # ...
end
```

Now you can get rid of the constructor (aka `initialize`) because there's nothing for it to do. Unless of course you're running your programm like this: `FizzBuzz.new(10)` Then you'd set the upper bound for fizz-buzzing in `inititialize` and would still use the rules defined by the constant.

Moving the range from the `to_s` in your example to `initialize` is probably a good idea because I'm not sure if `to_s` is supposed to support parameters. Having them set in `initialize` is more intuitive for someone who'd take over your code.

**Comment by kotp** [comment]
The way you are proving here, the way to change the rule would be to change the constant which would change the rules for ALL games, not just the one.

So the individual game is no longer able to happen.

Having it in the initialize where you can change each game, is what is allowed because of the constructor.

Thinking about to_s, it indeed can take a parameter and String.to_s for example does this as well as either Fixnum or Integer.

**Comment by lenn4rd** [comment]
I assumed that for this FizzBuzz game you'd want to follow the same rules for every game, i.e. always return Fizz if a number is divisible by 3 and Buzz if it is divisible for 5 and not the other way round. If you want to be able to make your own rules then passing rules to the constructor would be the way to go. The way you did it in #283 is right, but I'd move the default `rules` to a constant. In the constructor you'd initialize the rule set for the current game using the default rules plus the new rules you passed as a parameter hash.

```
class FizzBuzz
  RULES = { 3 => 'Fizz', 5 => 'Buzz' }

  def initialize(rules)
    @rules = RULES.merge(rules)
  end

  # ...
end
```

How you create `@rules` depends on whether you want to be able to override the default rules in `RULES` or not. In the example above for duplicate values (i.e. hash keys like 3) the second hash wins.

You're right, `to_s` does have parameters, but they're rather specifying the formatting as `Fixnum.to_s` does with `base = 10`. I'd advise against passing a parameter that influences program logic and using some kind of wrapper method instead, e.g. `f = FizzBuzz.new(10); f.play` where `f.play` loops 10 times each time calling `#to_s`.

**Comment by kotp** [comment]
Ah, I see, letting the class RULES constant be the default.

how will this work now for named parameters if I do give a range in the initialize ?  Though I don't want a range in the initialize because that limits that game pretty hard.  The to_s(1..15) means I get the output of that same object and just modify the formatting.  It doesn't modify the game, the game never changes.

**Comment by lenn4rd** [comment]
What do you mean by “limits the game”? It depends on whether you're seeing a FizzBuzz game as one move for one value or for several moves within the range you provided. The latter is what I find the most intuitive. In this case actually you'd initialize your FizzBuzz game with this range or may be better with the lower and upper bounds and transform that into a Ruby range within the constructor.

``` ruby
class FizzBuzz
  RULES = { 3 => 'Fizz', 5 => 'Buzz' }

  def initialize(lower = 1, upper = lower, rules = {})
    @rules = RULES.merge(rules)
    @range = lower..upper
  end

  # ...
end
```

Then you'd start playing the game by looping through `@range` and translating each number for every move.

**Comment by kotp** [comment]
I am not even positive how this conversation went from a module to a class. :)

Still, I probably would not us rules = {} but would provide the rules there, with a named parameters option at the end of the argument list to take the rules and assimilate them.  Providing an ordered argument option but a named argument option as well.

**Comment by kotp** [comment]
Yeah, in any code in my repository there is simply no initialize method to talk about.  I am now looking through your submissions to see where the conversation diverged.

**Comment by lenn4rd** [comment]
I took `initialize` from your comment in https://github.com/RubySteps/21-day-challenge/pull/283#discussion_r28624669

**Comment by kotp** [comment]
Oh, yeah. :)  I had forgotten.  Two different code bases... and two different assumption sets about the game.  Actually the code that was pasted from was under the assumption that the rules easily change and that other than the default sample of the game, that you would determine the player and the current number and work with them one at a time, like a circle of kids. Or a collection of circles of kids.

So it was kind of my fault to not sanitize it for the code I submitted.

So do you prefer working with the named arguments, or do you prefer taking the hash and merging later?  I prefer the named arguments and overwriting them if they want to change it.

For the module though, the user of the module would have the choice, I think.  That could be something to pair program on and verify.  You up for that?

**Comment by lenn4rd** [comment]
Writing this as a module vs. as a class depends on how you're going to use its logic. If you plan to include it into various other places creating it as a mixing would be the way to go but don't over-abstract things. I find it easier to understand if you have a concrete implementation without too much mixin things going on.

If you want to keep the parameter list on `initialize` short you can use setter methods to further specify how the game should behave, i.e. something like `add_rules(rules)` where the `rules` parameter is a hash and mandatory. You'd call this method right after your created the `FizzBuzz` instance.

**Comment by kotp** [comment]
I am not sure what I will do for day 6 yet.  But this has been a lot of good information.

Have you joined the [Gitter room](https://gitter.im/RubySteps/21-day-challenge) yet?

**Comment by kotp** [comment]
Writing this as a module was done so that others could use it as they see fit, mixing it in  So it isn't what I plan to include it into but what others plan to.  Is that the right direction to go?  In other words, I don't care if they have a initialize method that records the players name, or keeps track of the number of times they played, or are using the what_is method to check that players answer.... hopefully the module is non-restrictive enough to allow these things to happen.

And the to_s did not exist initially.  Honesty, I think I did it to produce a binary that easily and simply did a default run.  though the binary file allows for 1 or two arguments and shows what it is you want to show as a sample.  I think now that the bin file should probably just have its very own helper method for that.

**Comment by lenn4rd** [comment]
Now I understand why you chose this path. My approach is a bit different because I focus on what works best for me and the problem I'm trying to solve. If others find my solution useful that's fine and they're free to use my work and adapt it fit their situation but I can't foresee their plans. I think trying planning ahead and preparing one's own quite specific work for others to use them goes in the direction of [premature optimization](http://c2.com/cgi/wiki?PrematureOptimization). I think it's better to iterate on a solution and adapt it when requirements change over time than to try to plan far ahead. As Jason Fried and David Heinemeier Hansson put it in [Rework](http://37signals.com/rework/): “Planning is guessing.”

I haven't joined the Gitter room yet, but will do that within the next days. Also pairing up would be nice, I could try to set aside some time for that tomorrow on Sunday if you'd like.

**Comment by kotp** [comment]
Chat me on gitter when you get there or chat me on gmail.  From there we will figure out connection to pair program directly.

**Pull request merged**
