### PR TITLE
day four

### PR DESCRIPTION
**Pull request by reignmaker**

### CODE REVIEW

**Comment by kotp** [comment]
Short and to the point and valid.  MVP :)

LGTM

**Comment by patmaddox** [comment]
Where's the README? :(

**Comment by patmaddox** [comment]
do I not know about the `.dm` extension? :)

**Comment by kotp** [comment]
Technically, the extension should not matter as long as the README is there.  

And Github itself agrees.  See [the folder](https://github.com/reignmaker/21-day-challenge/tree/master/2_adventures/001/reignmaker/04) and you will see that Github thinks it should re displayed as a README regardless of the extension.

**Comment by patmaddox** [comment]
cool. good to know.

**Pull request merged**
