### PR TITLE
2015 04 16 rspec book chp02

### PR DESCRIPTION
**Pull request by edubs5**

### CODE REVIEW

**Comment by kotp** [comment]
Other than the day 3 commit in with this day 4 pull request, it looks good.  How or Why is the day 3 thing in this PR?

**Comment by edubs5** [comment]
I updated the day 3 file based on the tests I was doing for day 4 and the suggestion from you about ".zero?".

**Comment by patmaddox** [comment]
Go you!

**Comment by kotp** [comment]
I guess I wonder if the different day things should be separate pull requests, though this could be more work for @patmaddox  if we do keep these things separated in that way.

**Comment by patmaddox** [comment]
Starting next week, you'll want to do one pull request per day. If you want to update a previous days work as part of that pull request, that's fine. What you _don't_ want to do is submit all the work for two days in a single pull request... because that means you're a dollar late.

**Comment by kotp** [comment]
"dollar late" Nice cliche-contraction there... @patmaddox ...

[You know what they say...](https://youtu.be/UACh3uTfjjU?t=42)

**Comment by patmaddox** [comment]
@kotp ahahaha! What's funny is that I _thought_ I wrote "a day late" - and in my head, I thought "and a dollar short". Clearly I crossed wires in my brain there...

:heart: boondock saints

**Comment by kotp** [comment]
I have never heard the term 'cliche-contraction' so I think I may promote that so that centuries from now I will be know as the human that coined that phrase.  (I could be known for better things, I guess... like "Where's the Puppy?  In the pound!"  But that is another story.)

**Comment by edubs5** [comment]
Haha, thanks!  I'll note it on the commit message if I make changes to a previous day's file.

**Pull request merged**
