### PR TITLE
Day 15 challenge

### PR DESCRIPTION
**Pull request by aniruddhabarapatre**
Initial README

### CODE REVIEW

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
@aniruddhabarapatre can't merge this one... please fix the conflict & I'll merge

also, [please send each day in a separate pull request](https://github.com/RubySteps/21-day-challenge/wiki/Suggested-Git-Workflow#you-havent-merged-my-previous-days-work-what-do-i-do) in the future. thanks!

**Comment by kotp** [comment]
Can we label these when the message is "please fix the conflict" so that they are easier to find?

**Comment by patmaddox** [comment]
@kotp maybe I'm not understanding you... but I leave a message which notifies the person that they need to fix something. setting a label won't notify them

**Comment by kotp** [comment]
Setting a label will let those come out with just a click.  I had to add the login name in the search box to get to his three pull requests.

**Comment by kotp** [comment]
Though, yes, I can type in something like 'can't merge this one' in the search box.  But labels work better to group these.

**Comment by patmaddox** [comment]
oh. because you're fixing people's pull requests for them?

**Comment by kotp** [comment]
Only when they ask... But it could also be a management thing for @patmaddox to be able to come back and see if/when they get to be stale.  Less work in the long run for a potentially automated inclusion on the label.

**Comment by patmaddox** [comment]
@kotp I close pull requests if they haven't been merged / fixed in over a week.

I've closed nearly 700 pull requests so far so I think my management is okay ;)

I don't see where @aniruddhabarapatre requested help (and that's why we have these comment boxes, so we can communicate openly...) but perhaps you've established other channels for communication.

I'll use the "checked-fail" label when I get a PR that can't merge.

I would hope that we can keep project-relevant communication in the open, in PRs and issues & the chat, so others can benefit from our interactions & learning.

**Comment by kotp** [comment]
@patmaddox I am positive your management is. On the other hand, I am not sure how you manage stale pull requests.  Regardless of where things are done some things are 'back office' and unseeable, other than the result of the fruit of the labor.

As far as communication, I got a message via gitter.im, nothing that I initiated.  I did not even offer anyone to help with pull requets.  Pretty much have stopped communicating unless communicated to.

**Comment by patmaddox** [comment]
after I process open pull requests, there are only a small handful leftover (like, three). so I just wait and see if anything has happened in the past week. if not, I close them. they can always be re-opened

**Comment by kotp** [comment]
And then, I publicly, in these "comment boxes", observed what it was that I learned.  I learned that it took me longer to find the three issues concerned.  I would think that the "Communicating things learned" part was completed on my part.  Openly and appropriately.  We may yet hear from @aniruddhabarapatre about the things he learned about today, concerning the 3 pull requests.

So apparently, again, I have overstepped or done something wrong.

**Comment by patmaddox** [comment]
@kotp I don't know why you think you've overstepped or done something wrong.

I have no problem with people reaching out to one another, of course. That's why we have a wiki, a gitter channel, issues, a retrospective, and comments on pull requests. I encourage **everyone** to communicate in the open because then we can all benefit.

If someone wants to communicate in private, that's their choice, and I'm not going to try to stop them (not that I could).

**Comment by kotp** [comment]
Yes, but the "perhaps I have set up private channels" paraphrased... no.  And your defensive tone about a "could be used in management" that your management is just fine.  Just tonal problems, I am sure.  But I assure you I set no channels of communication with anyone.  The learning and git flow suggestions are in the README for day 16.  I got a request, worked through it, he was in attendance learning what it is he wanted to learn from it.

**Pull request merged**
