### PR TITLE
Day 21 challenge

### PR DESCRIPTION
**Pull request by aniruddhabarapatre**
Today's workflow

`git pull upstream master`
`git checkout -b day-21-challenge master`

Create README and commit it.

`git cherry-pick 4a749db`
`git push origin day-21-challenge`

### CODE REVIEW

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
@aniruddhabarapatre It looks like this is your fourth pull request with this same problem? I've responded in previous commits with suggested actions and links to documentation, and haven't heard anything back from you. The only advice I can give you now is to **create your branch off of upstream/master** rather than your dirty master branch.

If you need more help figuring this out, please ask for it. I believe I've done everything I can at this point in terms of explaining stuff and providing suggestions... and after getting no response from you, I'm at a loss for what to do now.

**Comment by aniruddhabarapatre** [comment]
@patmaddox I thought I followed the workflow that was mentioned by you on issue #825. 
Seems like I did create my branch on dirty master by doing `git checkout -b <branchname> master`. Again my assumption here was since I was doing `git pull upstream master`, I should be good.

I will close this branch and do `git checkout -b day-21 uptram/master`. Will this give me a clean and better solution?

**Comment by patmaddox** [comment]
@aniruddhabarapatre yes. see [this branch I created with one of your commits](https://github.com/patmaddox/21-day-challenge/tree/ani-day20). You can see that it is only 1 commit ahead of upstream/master

**Comment by patmaddox** [comment]
@aniruddhabarapatre `git pull upstream master` will do a fetch & merge, unless you use `--ff-only` as I document in the [suggested git workflow](https://github.com/RubySteps/21-day-challenge/wiki/Suggested-Git-Workflow).

The whole point of that workflow is to avoid problems like this :) and make it easy for you to do the right thing.

**Comment by aniruddhabarapatre** [comment]
Got it. I will try again this evening to fix all of my PR's. Thanks @patmaddox.

**Comment by kotp** [comment]
To be clear `git pull` always does a fetch and merge, unless used with the --rebase option, in which case it does a rebase rather than a merge. the `--ff-only`  restricts what it merges.

```
--ff-only  Refuse to merge and exit with a non-zero status
           unless the current HEAD is already up-to-date or 
           the merge can be resolved as a fast-forward."
```

**Comment by patmaddox** [comment]
closing because old

**Pull request closed without merging**
