### PR TITLE
Day 1 README

### PR DESCRIPTION
**Pull request by cypher**

### CODE REVIEW

**Comment by patmaddox** [comment]
Your pull request contains changes to files outside of the challenge and warmup directories. Please fix it!

2_adventures/002/cypher/01/README.md

---

Where's the README? :(

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
disregard that first message... my checker had adventure 1 hardcoded :blush:

**Comment by cypher** [comment]
No worries, was just confused :)

**Pull request merged**
