### PR TITLE
Create /2_adventures/001/jgodse/04_day4/README.md

### PR DESCRIPTION
**Pull request by jgodse**
Created day 4 challenge. Not much here today.

### CODE REVIEW

**Comment by kotp** [comment]
LGTM And I would second that 'want'. :)

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
what do you want to automate?

**Comment by jgodse** [comment]
I want to write a script which reads the day, figures out which day it is in the challenge, then create a jgodse/#{day}_day#{day}/README.md file, then do a "git add ." followed by a "git commit -m "Automatically generated for day #{day}"". Then it finishes with a "git push origin master".

**Comment by patmaddox** [comment]
:+1:  :100:

**Comment by kotp** [comment]
But, you would still need to have a pull request action done, right?  How would you facilitate that?

**Comment by jgodse** [comment]
Correct. However, that would still save a bit of work. I'm sure there must be a Git API to call to generate a pull request. Maybe I'll look into it.

**Pull request merged**
