### PR TITLE
Day 3 revision

### PR DESCRIPTION
**Pull request by Dino-Herbert**
Day 3 commit placed in correct subdirectory

### CODE REVIEW

**Comment by patmaddox** [comment]
Your pull request contains changes to files outside of the challenge and warmup directories. Please fix it!

3_heroes/dino-herbert/01/01_warmup/readme.md
3_heroes/dino-herbert/01/02_warmup/readme.md
3_heroes/dino-herbert/02/number_hole_puzzle.rb
3_heroes/dino-herbert/02/readme.md
3_heroes/dino-herbert/03/readme.md
3_heroes/dino-herbert/03/testscrape.rb

**Comment by patmaddox** [comment]
@Dino-Herbert there's probably a bit of confusion here because of how I numbered the three top-level directories... ALL of the adventure work goes under [2_adventures/001](https://github.com/RubySteps/21-day-challenge/tree/master/2_adventures) - please see the [wiki info on Adventures](https://github.com/RubySteps/21-day-challenge/wiki/Adventures). Thanks!

**Comment by patmaddox** [comment]
@Dino-Herbert to clarify a bit more... you should not be putting anything under `3_heroes` - that comes at the end of the challenge!

**Comment by Dino-Herbert** [comment]
@patmaddox Yes, I got the same comment from Victor about the 3_heroes directory.  In the 2nd "Day 3 commit"(b8a1fc4), I moved those files to 2_adventures/001/Dino-Herbert/03.  Please confirm that all is well.  Thanks!

**Comment by patmaddox** [comment]
@Dino-Herbert this pull request still contains the hero files... and as mentioned, your day 1 is a bit off. Here's what you need to do to be all set through day 3:
- create a `2_adventures/001/Dino-Herbert/01/README.md`
- `git rm -r 3_heroes/Dino-Herbert` to remove the hero files.

And I think you should be all set after that!

**Pull request merged**
