### PR TITLE
01 starting down the rabbit hole

### PR DESCRIPTION
**Pull request by chrisjones**

### CODE REVIEW

**Comment by patmaddox** [comment]
Your pull request contains changes to files outside of the challenge and warmup directories. Please fix it!

2_adventures/001/chrisjones/01-aesthetic/README.md

---

Where's the README? :(

**Comment by patmaddox** [comment]
@chrisjones this probably wasn't obvious because I hadn't created a directory for adventure 003... but your work should go in `2_adventures/003/chrisjone/01/README.md` instead (day 01 of adventure 003). Get that fixed up and I'll merge it!

**Comment by chrisjones** [comment]
@patmaddox Me thinks this is going to turn into a Git 21-day challenge. I'll send a new pull request shortly. Cheers

**Comment by patmaddox** [comment]
@chrisjones yep that's definitely a part of it :)  I think you want this closed, then... if I'm wrong, just go ahead and re-open

**Pull request closed without merging**
