### PR TITLE
Created first warmup.

### PR DESCRIPTION
**Pull request by kryptykphysh**
Hopefully, I'm doing this right.

### CODE REVIEW

**Comment by kotp** [comment]
This should exist in your own folder.  See below for Pat's specifically.  Yours should match but with your own name:

```
1_warmup/patmaddox
├── 01_my_first_warmup
│   └── README.md
```

And it is, so it looks good.

**Comment by kryptykphysh** [comment]
Outstanding. We're in Git territory I've never really had to tread before, so this could go horribly wrong.

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
looking good! one more and you're all warmed up...

**Pull request merged**
