### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by wattmatters**
Suckerific internet sure takes the fun out of learning.

### CODE REVIEW

**Comment by patmaddox** [comment]
Your pull request contains changes to files outside of the challenge and warmup directories. Please fix it!

2_adventures/001/10/README.md

---

Where's the README? :(

**Comment by patmaddox** [comment]
whoops! looks like you forgot your username :)

**Comment by wattmatters** [comment]
Not sure what happened there. This whole "no internet" thing sucks and I'm learning zippo as a result. Looks like I'm out of the challenge too, not that I was getting anywhere, just pfaffing about in the github web interface when I get a chance to log in.

**Comment by wattmatters** [comment]
recreated day 10 readme and a new one for day 11

**Comment by wattmatters** [comment]
and deleted the stray readme file

**Comment by patmaddox** [comment]
Go you!

**Pull request merged**
