### PR TITLE
Richard wigley

### PR DESCRIPTION
**Pull request by notapatch**
Hello you all.

_Slartibartfast_: You must come with me, or you'll be late. 
_Arthur Dent_: Late for what? 
_Slartibartfast_: Well, um, what's your name Earthman? 
_Arthur Dent_: Dent. Arthur Dent. 
_Slartibartfast_: Well, late as in _the late_ Dentarthurdent. It's a sort of threat. You see? 
_Arthur Dent_: No.

### CODE REVIEW

**Comment by patmaddox** [comment]
This pull request appears modify only your own files - nice work! Now it just needs final review from a human... (this comment was auto-generated :)

**Comment by patmaddox** [comment]
my heart skipped a beat when I saw @jimweirich's name in the file path...

**Comment by notapatch** [comment]
Heart infractions aside; I was thinking he was a good Ruby hero to have on the adventure ;-)

**Comment by patmaddox** [comment]
I like yer style

**Pull request merged**
