### PR TITLE
Commit with five warmups

### PR DESCRIPTION
**Pull request by Ravi279**
All five warmup's in one commit.

### CODE REVIEW

**Comment by kotp** [comment]
Welcome to the fun @Ravi279 .

**Comment by Ravi279** [comment]
Hi, thank you. @kotp

**Comment by Ravi279** [comment]
I think I messed up with my latest commit. The first two warm-up commits were fine, I saw the message   "can be automatically merged" when I made the pull request. But after the latest pull request I just made, it said "it cannot be merged automatically". (though the pull request was successful)

@kotp  Could you explain me the reason behind it?

**Comment by kotp** [comment]
If you made any changes in the files that were involved in the first two, that may be what is conflicting.  I can't see what is exactly causing the issue in this view.

**Comment by kotp** [comment]
Yeah, [look at this history](https://github.com/RubySteps/21-day-challenge/commits/52f5a3715213158fbe88822dafa0f568643757c2/1_warmup/ravi279) and you will see that there is prior history.  You may need to delve a little bit deeper to see the differences and what is conflicting.

**Comment by kotp** [comment]
If you look closely, you will see that the difference may be in whitespace even.  ( I am not sure on github how to show you the diffs... sorry, I seldom use the web interface.)

**Comment by Ravi279** [comment]
Yes, I did make changes to the files involved in the first two commits, with the present commit.

**Comment by Ravi279** [comment]
Do I need to commit and push the changes separately in this case? Is this the right way to do it?

**Comment by kotp** [comment]
On your repository, you are allowed to rebase and force the changes up to your "origin" remote repository.  But if @patmaddox has already accepted the pull requests from before, and it looks like he did, then this pull request will probably be denied.

**Comment by kotp** [comment]
Or he will ask you to resolve the conflicts.  It is unlikely that he will, as that sets a kind of bad precedence and it takes away from the learning experience.

**Comment by kotp** [comment]
Part of the issue is also that you are doing this from your master branch.  I see that you have also done pull requests from your branch "patch-1" and so you are aware of how to set up a branch and do pull requests from there.   You may want to close this PR and create a new clean one.  It is up to you.

**Comment by Ravi279** [comment]
Okay, I guess I will close this PR and do a clean new one. Thanks for your input @kotp :+1:

**Pull request closed without merging**
