### PR TITLE
My submission for day 4.

### PR DESCRIPTION
**Pull request by luisalima**
A rather uninspired submission for day 4 after a long looong day... But if you are thinking about coding on an ipad, might come in handy :smile_cat:

### CODE REVIEW

**Comment by kotp** [comment]
LGTM and good information!

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
Nice I wonder if [cloud9](https://c9.io) works on iPad too? When I was looking at web-based dev tools, I preferred c9 over nitrous because c9 supported GitHub login...

**Comment by luisalima** [comment]
That's a good question. Nitrous' devbox prices are also a bit on the steep side. There's also [codeanywhere](https://codeanywhere.com/). I'll check when I have the time :)

**Pull request merged**
