### PR TITLE
Luisa Lima's day 2

### PR DESCRIPTION
**Pull request by luisalima**
Hi @patmaddox I hope I'm not missing anything? A bit :confused: here...

### CODE REVIEW

**Comment by luisalima** [comment]
@patmaddox I closed this because I want to cherry-pick only the commit that matters.

**Comment by luisalima** [comment]
@patmaddox actually... how do I cherry-pick https://github.com/luisalima/21-day-challenge/commit/fff24a967873da5ecee32cfa593c6ed8f2b6a773 only? Or should I have reforked the project?

**Comment by luisalima** [comment]
@patmaddox -- I was stupid .. face palm! I should have synced the fork first.

**Comment by patmaddox** [comment]
@luisalima I didn't know about syncing the fork... I'll have to check out that link later (and it's now in the wiki, thanks to you)

**Comment by luisalima** [comment]
@patmaddox :smiley_cat:

**Pull request closed without merging**
