### PR TITLE
4th day 

### PR DESCRIPTION
**Pull request by sbartek**
Starting with a project. No ruby code so far though.

### CODE REVIEW

**Comment by patmaddox** [comment]
Go you!

**Comment by kotp** [comment]
LGTM

**Comment by patmaddox** [comment]
this is not silly at all, this is awesome! I love the design image and domain-specific data... I'm looking forward to see what you do with this :)

**Comment by sbartek** [comment]
Thanks for comment! Now I'm quite motivated to go on.

**Pull request merged**
