### PR TITLE
warming up

### PR DESCRIPTION
**Pull request by kangkyu**

### CODE REVIEW

**Comment by kotp** [comment]
Directories are good, but really this should be 5 different pull requests.  Two for warmup, and one for each day.  @patmaddox  will be in before [RSST](http://www.rubysteps.com/rst/) end of day to answer that question.  But the parts do comply, with the expected requirements.

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
this is fine... I've extended the free pass through the first week. Start week 2, you'll want one pull request per day!

**Comment by kotp** [comment]
YAY!  I would have had my son join in, but told him there was only 2 hours to GTD.  Oh well, maybe next month.

**Comment by patmaddox** [comment]
@kotp so does that mean your son will join in now? :)

**Comment by kotp** [comment]
No, you said the slip in days is forgiven, not the late sign up after day 3.

**Comment by kotp** [comment]
And now it is way after that 2 hours before the end of day 3.

**Comment by patmaddox** [comment]
ah you're right, I hadn't thought of that. and yes, I've already changed the signup form to put people on the list for next month. so... next month!

**Pull request merged**
