### PR TITLE
Day 5 - Learning about gaps in knowledge

### PR DESCRIPTION
**Pull request by liamseanbrady**
Early start and busy day tomorrow, so have to do my Day 5 challenge tonight.

Hit a roadblock with testing a system call cleanly. Frustrating, but I can already tell building this Trello client this will be a fantastic learning experience!

### CODE REVIEW

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
One thing that may help is to test the things that are easy, and punt on the things that are hard. That doesn't mean you _never_ test the things that are hard, or should not learn how... but in the sake of forward progress, and simplicity, you're often better off creating simple Ruby objects that you can test, and then moving the hard-to-test stuff in to its own space.

You'd like to test that hard stuff eventually... but mostly tested code that works is better than code that doesn't work because you didn't get around to writing it ;)

You can see that in my day 04 work where [I have tested](https://github.com/RubySteps/21-day-challenge/blob/master/2_adventures/001/patmaddox/04/validator_spec.rb) a good chunk of my [business logic](https://github.com/RubySteps/21-day-challenge/blob/master/2_adventures/001/patmaddox/04/validator.rb#L6) and separated the [GitHub interaction stuff to its own method](https://github.com/RubySteps/21-day-challenge/blob/master/2_adventures/001/patmaddox/04/validator.rb#L32).

Remember, perfect is the enemy of good, and you can always Turn up the Good!

**Comment by kotp** [comment]
Can you identify which thing you are having a hard time with?  And link it here?  I am positive you will get some assistance with it.

**Comment by liamseanbrady** [comment]
@kotp I'm planning to get back onto Trello Rat on Day 08 so I'll definitely hang out on Gitter and hopefully figure out what the best way is to test specific things. It would be awesome to get your input on that!

@RobAWilkinson thanks! Haven't had much chance to practice stubbing and mocking up to this point, but I'll definitely put reading about how to do this with Minitest on my todo list.

@patmaddox I stuck your advice today in my Day 06 code and it made things so much easier! Really appreciate you taking the time to help me out.

**Pull request merged**
