### PR TITLE
Day One Challenge

### PR DESCRIPTION
**Pull request by ladanazita**

### CODE REVIEW

**Comment by patmaddox** [comment]
hey don't delete my README :)  send a version w/o the deleted README commit and I'll merge. make sure to not include the delete commit at all, rather than just reverting it. that file was never supposed to get deleted, and we want the git history to reflect it

**Comment by ladanazita** [comment]
Ahh! Whoops! I had made a README in the wrong folder and must have
mistakenly deleted yours!!! So sorry! That was my first commit so I will
have to redo the whole thing! Will resend it soon

On Mon, Apr 13, 2015 at 8:56 PM, Pat Maddox notifications@github.com
wrote:

> hey don't delete my README :) send a version w/o the deleted README commit
> and I'll merge. make sure to not include the delete commit at all, rather
> than just reverting it. that file was never supposed to get deleted, and we
> want the git history to reflect it
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RubySteps/21-day-challenge/pull/134#issuecomment-92590833
> .

## 

_Ladan Nasserian_
Marketing Professional

Cell: (310) 594-0780
Email: ladannasserian@gmail.com
- www.linkedin.com/pub/ladan-nasserian/a6/5b5/158/

**Comment by patmaddox** [comment]
@ladanazita don't sweat it... that's why we use git in this manner! you didn't break anything - the problem exists in your own repo.

and guess what! you don't need to redo the whole thing... you have (at least) two options here: you can use [git cherry-pick](http://git-scm.com/docs/git-cherry-pick) or you can rewrite history with [interactive rebasing](http://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)

both are very powerful tools, and demonstrate why git is awesome! check em out...

**Comment by ladanazita** [comment]
Mind. Blown. Genius. So excited to learn more!!!! Woot woot 💃💃

Ladan Nasserian

**Pull request closed without merging**
