### PR TITLE
 Day 1: Initial commit for the 2nd Adventure

### PR DESCRIPTION
**Pull request by JonKernPA**
I sure hope this is starting off as a "clean" PR. I did end up pruning my repo, as I did have some cruft.

### CODE REVIEW

**Comment by patmaddox** [comment]
Your pull request contains changes to files outside of the challenge and warmup directories. Please fix it!

2_adventures/002/jonkernpa/01/README.md

---

Where's the README? :(

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
all good! btw it's easy enough to tell when the PR is nice and clean... in this case it shows one commit changing one file. in the bad ones, it's been hundreds of commit changing lots of other people's files...

disregard that first message... my checker had adventure 1 hardcoded :blush:

**Comment by JonKernPA** [comment]
kewl

**Pull request merged**
