### PR TITLE
01 first warmup

### PR DESCRIPTION
**Pull request by zshnr**
should be ok now I think. So sorry about these stupid mistakes.

### CODE REVIEW

**Comment by patmaddox** [comment]
@zrasool88 cool! Can you please do me a favor and rebase it so it doesn't have "deleted useless files" and the revert commit? Let's try to keep it as a nice clean history...

there are a couple of ways you could do this. you could use an [interactive rebase](http://www.git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Reordering-Commits) or you could make a new branch and [cherry-pick](http://git-scm.com/docs/git-cherry-pick) the commits.

As soon as you get rid of 17a04de and 8a139b1 I'll merge and you're all set!

**Comment by patmaddox** [comment]
you know what? it's a warmup, I'll allow it :)  plus it shows people how to revert if they need to!

**Comment by zshnr** [comment]
Thanks a lot, Pat! And again, sorry for this =/

**Comment by patmaddox** [comment]
no sweat, that's why we do the warmup!

**Comment by kotp** [comment]
And it is good as we learn more from the things we initially do wrong than we learn from doing it correctly in the first place.

**Pull request merged**
