### PR TITLE
Day 2

### PR DESCRIPTION
**Pull request by cypher**

### CODE REVIEW

**Comment by patmaddox** [comment]
this is about an hour early for day 2... is my documentation bad or did you just jump the gun?

**Comment by cypher** [comment]
No, just me confused about time zones.

**Comment by patmaddox** [comment]
okay. I realize the [RST page](http://www.rubysteps.com/rst/#002) isn't awesome, but the clock up top shows the current date and time as it relates to the challenge.

a better counter would be worthwhile... and I think @kotp has a tool (or adapted someone else's?) that shows day information?

**Comment by cypher** [comment]
True, but the clock requires flash, and I don't have that installed :)

Anyway, should I retract the pull request, and submit it again tomorrow? Or just leave it up?

**Comment by patmaddox** [comment]
no it's fine. first three days are a free pass anyway :)

**Pull request merged**
