### PR TITLE
DAY 2

### PR DESCRIPTION
**Pull request by amaliahern**
After fixin some problems with my repo, I am here again.
Thanks Pat and Viktor, I got it!!

### CODE REVIEW

**Comment by kotp** [comment]
This is showing some conficts?  Do you need to close your old pull requests?  Not looking very closely at it, but that is my first reaction.

**Comment by patmaddox** [comment]
I already merged the previous pull request... so the split ones aren't needed.

@amaliahern I'm glad you learned what you needed to :)  as mentioned earlier, the free pass applies through day 3 so you were okay on that count...

also, even if you _do_ inadvertently submit two days in one pull request because your new branch includes the previous day's work, that's totally fine. The pull request doesn't _have_ to be limited to one day's work - it's just that you need one pull request per day...

I would suggest closing these two pull requests as the work as already been merged.

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
closing because of what I mentioned earlier... @amaliahern if you have questions please let me know! (you should still be able to comment in here)

**Pull request closed without merging**
