### PR TITLE
Create a small twitter client to post things, leave out access_tokens.ym...

### PR DESCRIPTION
**Pull request by awochna**
...l information.

### CODE REVIEW

**Comment by patmaddox** [comment]
This pull request appears modify only your own files - nice work! Now it just needs final review from a human... (this comment was auto-generated :)

**Comment by patmaddox** [comment]
@awochna for future reference, you can list files in a [.gitignore](https://help.github.com/articles/ignoring-files/) to make git... ignore them :)

so your access_tokens.yml is a great candidate for it - that way you don't have to worry about accidentally uploading your info.

if you do choose to go this route (which I highly recommend) then you'll want to `git rm access_tokens.yml` _before_ you do the `.gitignore`... because `.gitignore` will cause git to ignore any changes made to listed files - including removing them! (unless you use a `git rm -f`... I think).

Finally, I would double-check your public history and make sure that the real access tokens don't show up anywhere. Maybe you did a flatten before this pull request... but real commits still show up in your own repo. I'm not sure, you'll have to look.

I suspect you know at least some of this stuff, but better to be safe than sorry!

btw, having a `access_tokens.yml.example` file checked in to git, with `access_tokens.yml` in `.gitignore` is a very common - and helpful - pattern.

**Comment by patmaddox** [comment]
also... cool!!! :)

**Comment by awochna** [comment]
I probably should have done the access_tokens.yml.example there. I have a separate copy on my local machine that has the real things.

Don't worry. I _git_ it.

**Comment by patmaddox** [comment]
:100:

**Comment by kotp** [comment]
What you said @awochna I was just writing a quick note about the `some.example` style file.

Additional points for writing a rake task that asks for the required information and creates that required file interactively. :)

**Comment by awochna** [comment]
I'll have to make that suggestion on day 5, @kotp. I already have a plan for day 4.

**Pull request merged**
