### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Ravi279**
Wohooo!

I did make a PR without any issues (with some help ofcourse) Thank you @kotp :+1:

### CODE REVIEW

**Comment by kotp** [comment]
Now you just need the `2_adventures/001/<yourname><0[d]_your_descriptions>` folders for the 1-7th days.

**Comment by Ravi279** [comment]
Okay. Can I just have folder 7 inside "2_adventures/001/<my_name>" because I did not do anything for previous six days related or something which can be rated as an adventure? @kotp

**Comment by patmaddox** [comment]
this is the adventure! you can create only day 07 if you want... but if you want to successfully complete the challenge, you'll need folders for all 21 days. and today's your last day to catch up on the first week. so if you want to successfully complete the challenge, get them all in soon :)

**Comment by Ravi279** [comment]
Okay @patmaddox.

**Comment by kotp** [comment]
@Ravi279 You are off to a good start... as you have created already 7 README files.  As per requirement is a folder a day (in the prescribed naming convention) with a README.md (though the extension may be something else, I think was the agreement) for each folder.

**Comment by Ravi279** [comment]
@patmaddox / @ktop Do I need to make a new PR for the adventures only after the present PR is accepted?

**Comment by Ravi279** [comment]
No I take back my question, that was dumb. But I'm surely learning more than what I'm actually doing here.

**Comment by kotp** [comment]
You can create a new branch, do the required PR's from each branch.  (Though I think that due to the slip-policy in place for now you can do one PR and have the full set of changes in there.)  Also, I am not leadership here, just so you know.  @patmaddox has final say.

**Comment by patmaddox** [comment]
@Ravi279 you can create a new PR even if the previous one hasn't been accepted. git is pretty neat that way.

You have two choices... one is to send your new PR including commits from the old PR. The old commits just won't show up in the new PR once the old PR is accepted (that sounds a bit confusing...)

Another approach is to create a new branch directly off of master, for each PR. That feels cleaner to me, but it really doesn't matter ;)

**Comment by Ravi279** [comment]
@patmaddox Okay, I got it. I guess I will have to follow the second one as you said the first one is a bit confusing.

**Comment by patmaddox** [comment]
Go you!

**Pull request merged**
