### PR TITLE
First and Second Warm Up

### PR DESCRIPTION
**Pull request by ravencovington**

### CODE REVIEW

**Comment by patmaddox** [comment]
@ravencovington please rename your directories so they match your GitHub username, thanks :)

you should be able to do it simply with a `git mv raven ravencovington`, commit, and push to the same branch

**Comment by patmaddox** [comment]
@ravencovington one other thing, your personal directory needs to go in the 1_warmup directory. so to meet [the warmup criteria](https://github.com/RubySteps/21-day-challenge/tree/master/1_warmup) I think you'll want to do:

`git mv raven 1_warmup/ravencovington`

This will move your top-level `raven` directory in to the `1_warmup` directory, and match your username.

If you push that change to the same branch on GitHub, it will automatically update this pull request with the new commit. Please leave a comment here though so I know that you've made a new change :)

**Comment by ravencovington** [comment]
@patmaddox I believe I've fixed it

**Comment by patmaddox** [comment]
@ravencovington a couple quick changes to make, and then you're all done:
- include a README in your second directory as well (there needs to be a README for every step of the challenge, so I'm requiring it for the warmup as well)
- go ahead and delete the extra `raven/01/README.md` and `raven/02/hello.rb` files

**Comment by ravencovington** [comment]
@patmaddox Sorry, I think it's good to go now.

**Comment by patmaddox** [comment]
no apology needed! good to go :)

**Pull request merged**
