### PR TITLE
Day 6th

### PR DESCRIPTION
**Pull request by sbartek**
Show must go on.

### CODE REVIEW

**Comment by kotp** [comment]
:camera: I was going to say lgtm, but perhaps a photograph is even better. (Don't they last longer?)

**Comment by sbartek** [comment]
I'm not sure what you mean by that. :) But it definitely sounds nice. Thanks.

**Comment by kotp** [comment]
Childish saying "Take a picture, it lasts longer"... rather than looks good to me.  Just a silly reference for good looking pull request.

**Comment by patmaddox** [comment]
Go you!

**Pull request merged**
