### PR TITLE
Got notes returning when given a major/ minor chord

### PR DESCRIPTION
**Pull request by RobAWilkinson**

### CODE REVIEW

**Comment by kotp** [comment]
Missing the required README file for the day's pull request.  Otherwise looks good to me.

**Comment by RobAWilkinson** [comment]
@kotp ahhhhh so true haha, so busy writing tests forgot to write documentation lol

**Comment by patmaddox** [comment]
Where's the README? :(

**Comment by RobAWilkinson** [comment]
Readme in!

**Comment by patmaddox** [comment]
I love this! and your code is starting to look cleaner these days :)

**Pull request merged**
