### PR TITLE
Day 4 Retrospective

### PR DESCRIPTION
**Pull request by wattmatters**
It's been a massive day for me personally, so unlikely to do much more today hence just submitting this as my Day 4 input before it all gets away from me.

### CODE REVIEW

**Comment by kotp** [comment]
:100:  This will indeed work from master for now, and it is OK, but you are right, later as things become more complex  you will want to leave master and work in a branch.

So much to learn, details, nuances, and dashes and hopefully less dots.  (Dots are dangerous... ) but we will get to that.  For now, you are doing well, and this will become routine and soon you will understand not only understand the how, but also the why.

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
it can take a while but you'll get the hang of it! The [git documentation](http://git-scm.com) is quite awesome too...

**Comment by kotp** [comment]
The git documentation is a model of how documentation should be.  Just like the Linux documentation.  I am sure Linus had a large influence in that happening, but I couldn't testify to it.

**Pull request merged**
