### PR TITLE
Date suffix

### PR DESCRIPTION
**Pull request by 7sun**

### CODE REVIEW

**Comment by patmaddox** [comment]
This pull request appears modify only your own files - nice work! Now it just needs final review from a human... (this comment was auto-generated :)

**Comment by patmaddox** [comment]
@7sun the README is the key... I'm REALLY happy to see you writing Ruby code. But to satisfy the daily requirements, you need a README...

**Comment by 7sun** [comment]
Added the readme as requested for my super fancy method. Also adds the day 4 directory now with a readme.

**Comment by kotp** [comment]
It probably should really be two different pull requests.

**Pull request merged**
