### PR TITLE
Add cypher's files for day 3

### PR DESCRIPTION
**Pull request by cypher**

### CODE REVIEW

**Comment by patmaddox** [comment]
This pull request appears modify only your own files - nice work! Now it just needs final review from a human... (this comment was auto-generated :)

**Comment by patmaddox** [comment]
dang! sometimes life forces your hand... best of luck to you @cypher

**Comment by cypher** [comment]
Thanks! At first, I was a bit bummed, but as I wrote, I wanted to go freelance at some point anyway, and now seems as good a time as any (especially if they give me that contract).

**Comment by patmaddox** [comment]
yeah it sounds like a good opportunity to transition from employee work to freelancing :)

**Pull request merged**
