### PR TITLE
Day 8: Rubygem to calculate remaining time till challenge deadline

### PR DESCRIPTION
**Pull request by skahlert**
Gem version of my Day5 challenge, suggested by @kotp

### CODE REVIEW

**Comment by kotp** [comment]
You don't have an opt-in on this, so I won't critique it, but in a general way just to say that I cloned your repository and build and installed the gem and it works.  Of course, you already know this.

**Comment by skahlert** [comment]
@kotp By all means... I opt-in!
I'd love to hear any feedback. Positive or negative!

**Comment by kotp** [comment]
Here we go. :) 

When I installed it directly from this project, I read the readme to get the relevant information required to use this tool, and looked in the bin folder to see the executable.

The gemspec has a `post_install_message` which can help to orient users to the tool they are installing, as well as any 'branding' that you may want to reveal.

`spec.post_install_message = "Thanks for installing!"`

This message can be useful in helping folks know what the executable file is when they do a `gem install awesome_tool` especially when that executable is different from the name of the gem.

Of course your readme covers these things so it is just an additional nicity to add it in the install process.

There could be a `~/.rubysteps` configuration file where the start date could be set, and so would be useful for future iterations.  Have the requirement to include the time zone however you want it to be expressed, and it is useful for more than just RubySteps.

**Comment by patmaddox** [comment]
Go you!

**Pull request merged**
