### PR TITLE
DAY 1: starting the second adventure

### PR DESCRIPTION
**Pull request by amaliahern**

### CODE REVIEW

**Comment by amaliahern** [comment]
I think I did one PR for first two days, ohhh :-(

**Comment by kotp** [comment]
First three days there is a "slip-factor", I think.  So you should still be good.  Perhaps a good opportunity for the practice of splitting them out into two pull requests, but other than that, I think you are probably good.

**Comment by amaliahern** [comment]
Hi Victor,

Could you suggest me how I can split my PR? I think it would be great.
I thought if I made PR from different branch it will be different PR. I was
wrong. :-(
It is nice to learn ;-)

Thanks in advance!!
Amalia

2015-05-07 5:47 GMT+02:00 Victor Goff notifications@github.com:

> First three days there is a "slip-factor", I think. So you should still be
> good. Perhaps a good opportunity for the practice of splitting them out
> into two pull requests, but other than that, I think you are probably good.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RubySteps/21-day-challenge/pull/900#issuecomment-99702184
> .

## 

http://mazapanfeliz.es
http://twitter.com/amaliahern

**Comment by patmaddox** [comment]
Go you!

**Comment by patmaddox** [comment]
@amaliahern you would need to push out two branches, and send pull requests from each branch. I think [this wiki information](https://github.com/RubySteps/21-day-challenge/wiki/Suggested-Git-Workflow#you-havent-merged-my-previous-days-work-what-do-i-do) will help out.

**Pull request merged**
